### ISSUE TITLE
When starting the job service, repo "job_type" can be resolved from a module

### ISSUE THREAD

**Issue by leebow** [happner/tracey#2]
Currently the repos defined in the tracey.yml define __job_type_, eg:

```
...
repos:
  - owner: 'happner' #owner of repo
    name: 'tracey' #name, combined to form the full name tracey/happner
    testFolder: './test' #folder containing tests to be benchmarked
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance_tracker'
...
```

Job type should also be able to be resolved from a module as well as a folder. In the job service **__do** method, a job runner is instantiated based on finding it in the **/lib/job_types** folder. We need this code to also be able to look for a matching module if there is no match in the **/lib/job_types** folder.
