### ISSUE TITLE
Configuration should allow jobs to specify a cron-like schedule

### ISSUE THREAD

**Issue by leebow** [happner/tracey#4]
This allows jobs to run on a specified schedule rather than only when a Github webhook is activated.

**Comment by leebow** [comment]
The .tracey.yml configuration file now allows the **schedule** property on job definitions, eg:

```yml
  - owner: 'happner' #owner of repo
    name: 'happn' #name, combined to form the full name tracey/happner
    testFolder: './test' #folder containing tests to be benchmarked
    node_js:
      - '7'
      - '0.10'
    job_type: 'performance-tracker-lite'
    schedule: '00 40 00 * * *'  # pattern: seconds | minute | hour | day of month | month | day of week
```
